repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        name: Rust fmt
        description: Format Rust code with rustfmt
        entry: cargo fmt
        language: system
        files: \.rs$
        pass_filenames: false
      - id: cargo-check
        name: Rust cargo check
        description: Check Rust code with cargo check
        entry: cargo check
        language: system
        files: \.rs$
        pass_filenames: false
      - id: clippy
        name: Rust clippy
        description: Lint Rust code with clippy
        entry: cargo clippy
        language: system
        files: \.rs$
        pass_filenames: false
        args: ['--', '-D', 'warnings']

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        name: Markdown lint
        description: Lint markdown files
        args: ['--fix']
        files: \.md$
