version: '3.8'

services:
  step-ca:
    image: smallstep/step-ca:latest
    container_name: step-ca-server
    ports:
      - "9000:9000"
    volumes:
      - step_ca_data:/home/step
      - step_ca_config:/etc/step-ca
    environment:
      - DOCKER_STEPCA_INIT_NAME=Internal PKI CA
      - DOCKER_STEPCA_INIT_DNS_NAMES=ca.company.internal,localhost
      - DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT=true
      - DOCKER_STEPCA_INIT_ACME=true
    networks:
      - cert-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "step", "ca", "health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  step-ca-init:
    image: smallstep/step-ca:latest
    container_name: step-ca-init
    volumes:
      - step_ca_data:/home/step
      - step_ca_config:/etc/step-ca
    environment:
      - DOCKER_STEPCA_INIT_NAME=Internal PKI CA
      - DOCKER_STEPCA_INIT_DNS_NAMES=ca.company.internal,localhost
      - DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT=true
      - DOCKER_STEPCA_INIT_ACME=true
      - DOCKER_STEPCA_INIT_PASSWORD=changeme
    command: |
      sh -c "
        if [ ! -f /home/step/config/ca.json ]; then
          echo 'Initializing Step CA...'
          step ca init --deployment-type=standalone \
            --name='Internal PKI CA' \
            --dns='ca.company.internal,localhost' \
            --address=':9000' \
            --provisioner='admin' \
            --password-file=<(echo 'changeme')

          echo 'Enabling ACME provisioner...'
          step ca provisioner add acme --type=ACME

          echo 'Step CA initialized successfully'
        else
          echo 'Step CA already initialized'
        fi
      "
    depends_on:
      - step-ca
    networks:
      - cert-network
    restart: "no"

  # Optional: Step CA Admin UI
  step-ca-ui:
    image: smallstep/step-ca:latest
    container_name: step-ca-ui
    ports:
      - "3000:3000"
    volumes:
      - step_ca_data:/home/step:ro
    environment:
      - STEP_CA_URL=https://step-ca:9000
    command: ["step-ca-ui", "--ca-url", "https://step-ca:9000"]
    depends_on:
      - step-ca
    networks:
      - cert-network
    restart: unless-stopped

volumes:
  step_ca_data:
    driver: local
  step_ca_config:
    driver: local

networks:
  cert-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
