version: '3.8'

# Example: Nginx service with cert-agent integration
services:
  # Main application service
  nginx:
    image: nginx:alpine
    container_name: nginx-web-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Certificate access (read-only)
      - nginx_certs:/etc/ssl/certs:ro

      # Nginx configuration
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
    depends_on:
      - nginx-cert-agent
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Certificate agent for nginx
  nginx-cert-agent:
    image: appleparan/cert-agent:latest
    container_name: nginx-cert-agent
    environment:
      # Service-specific configuration
      - CERT_DOMAINS=web.company.internal,www.company.internal
      - STEP_CA_URL=https://ca.company.internal:9000
      - RELOAD_COMMAND=docker exec nginx nginx -s reload
      - SERVICE_NAME=nginx-web-server

      # Renewal settings
      - RENEWAL_DAYS=7
      - CHECK_INTERVAL=6h
      - CERT_VALIDITY=30d

      # Step CA authentication
      - STEP_CA_PROVISIONER=acme

      # Notification settings
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL:-}
    volumes:
      # Certificate storage (read-write)
      - nginx_certs:/certs:rw

      # Docker socket for nginx reload
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app-network
      - cert-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/health-check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  nginx_certs:
    driver: local

networks:
  app-network:
    driver: bridge
  cert-network:
    external: true
