# Step CA Infrastructure - Simplified Single Container Setup
#
# Quick Start:
# 1. Start Step CA: docker-compose up -d
# 2. Bootstrap client: ./bootstrap.sh
# 3. Test connection: step ca health
#
version: '3.8'

services:
  step-ca:
    image: smallstep/step-ca:latest
    container_name: step-ca
    ports:
      - "${STEP_CA_PORT:-9000}:9000"
    environment:
      - DOCKER_STEPCA_INIT_NAME=${STEP_CA_NAME:-Smallstep}
      - DOCKER_STEPCA_INIT_DNS_NAMES=${STEP_CA_DNS:-localhost,ca.company.internal}
      - DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT=true
      - DOCKER_STEPCA_INIT_ACME=true
    volumes:
      - step:/home/step
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "step", "ca", "health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  step:
    driver: local
